version: "3.8"
services:
  node:
    build:
      context: ./docker/node
    tty: true
    volumes:
      - ./react:/var/www/src
      - node_modules:/var/www/src/node_modules

    ports:
      - "3000:3000"

volumes:
  node_modules:
